name: Scrape RSS and commit CSV

on:
  schedule:
    - cron: '*/10 * * * *'  # every 10 minutes
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pandas feedparser newspaper3k

    - name: Run scraper
      run: python rss_scraper.py

    - name: Commit CSV to repo
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add data/articles.csv
        git commit -m "📰 Update articles.csv [skip ci]" || echo "No changes to commit"
        git push
